# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apparmor.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='apparmor.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x61pparmor.proto\"\'\n\taa_policy\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0c\n\x04\x62lob\x18\x02 \x02(\x0c\"]\n\x0c\x61\x61_namespace\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x1c\n\x08policies\x18\x02 \x03(\x0b\x32\n.aa_policy\x12!\n\nnamespaces\x18\x03 \x03(\x0b\x32\r.aa_namespace\"3\n\x0e\x61pparmor_entry\x12!\n\nnamespaces\x18\x01 \x03(\x0b\x32\r.aa_namespace'
)




_AA_POLICY = _descriptor.Descriptor(
  name='aa_policy',
  full_name='aa_policy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='aa_policy.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='blob', full_name='aa_policy.blob', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=57,
)


_AA_NAMESPACE = _descriptor.Descriptor(
  name='aa_namespace',
  full_name='aa_namespace',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='aa_namespace.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='policies', full_name='aa_namespace.policies', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='namespaces', full_name='aa_namespace.namespaces', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=152,
)


_APPARMOR_ENTRY = _descriptor.Descriptor(
  name='apparmor_entry',
  full_name='apparmor_entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='namespaces', full_name='apparmor_entry.namespaces', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=205,
)

_AA_NAMESPACE.fields_by_name['policies'].message_type = _AA_POLICY
_AA_NAMESPACE.fields_by_name['namespaces'].message_type = _AA_NAMESPACE
_APPARMOR_ENTRY.fields_by_name['namespaces'].message_type = _AA_NAMESPACE
DESCRIPTOR.message_types_by_name['aa_policy'] = _AA_POLICY
DESCRIPTOR.message_types_by_name['aa_namespace'] = _AA_NAMESPACE
DESCRIPTOR.message_types_by_name['apparmor_entry'] = _APPARMOR_ENTRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

aa_policy = _reflection.GeneratedProtocolMessageType('aa_policy', (_message.Message,), {
  'DESCRIPTOR' : _AA_POLICY,
  '__module__' : 'apparmor_pb2'
  # @@protoc_insertion_point(class_scope:aa_policy)
  })
_sym_db.RegisterMessage(aa_policy)

aa_namespace = _reflection.GeneratedProtocolMessageType('aa_namespace', (_message.Message,), {
  'DESCRIPTOR' : _AA_NAMESPACE,
  '__module__' : 'apparmor_pb2'
  # @@protoc_insertion_point(class_scope:aa_namespace)
  })
_sym_db.RegisterMessage(aa_namespace)

apparmor_entry = _reflection.GeneratedProtocolMessageType('apparmor_entry', (_message.Message,), {
  'DESCRIPTOR' : _APPARMOR_ENTRY,
  '__module__' : 'apparmor_pb2'
  # @@protoc_insertion_point(class_scope:apparmor_entry)
  })
_sym_db.RegisterMessage(apparmor_entry)


# @@protoc_insertion_point(module_scope)
